import type { Book } from '@/types/content';

export const books: Book[] = [
  {
    id: 'designing-data',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    coverColor: '#2D4A7A',
    spineColor: '#1A3156',
    category: 'engineering',
    takeaway: 'The best systems book I\'ve read — it changed how I think about data flow, consistency, and distributed systems trade-offs.',
  },
  {
    id: 'attention-all',
    title: 'Attention Is All You Need',
    author: 'Vaswani et al.',
    coverColor: '#8B4513',
    spineColor: '#6B3410',
    category: 'ai-ml',
    takeaway: 'The paper that rewired modern AI. Understanding transformers deeply is non-negotiable for working with LLMs.',
  },
  {
    id: 'deep-learning',
    title: 'Deep Learning',
    author: 'Goodfellow, Bengio, Courville',
    coverColor: '#4A0E4E',
    spineColor: '#380A3B',
    category: 'ai-ml',
    takeaway: 'The mathematical foundations you need before you can meaningfully contribute to AI research.',
  },
  {
    id: 'clean-code',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    coverColor: '#1B5E20',
    spineColor: '#0D3B11',
    category: 'engineering',
    takeaway: 'Code is read far more than it\'s written. This book made me care about naming, structure, and readability.',
  },
  {
    id: 'sapiens',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    coverColor: '#BF360C',
    spineColor: '#8C2809',
    category: 'philosophy',
    takeaway: 'Understanding how humans coordinate at scale gives you a different lens for designing systems that serve them.',
  },
  {
    id: 'atomic-habits',
    title: 'Atomic Habits',
    author: 'James Clear',
    coverColor: '#F57F17',
    spineColor: '#C66A00',
    category: 'leadership',
    takeaway: 'Small systems beat big goals. This philosophy shapes how I approach both code and personal growth.',
  },
  {
    id: 'alchemist',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    coverColor: '#E65100',
    spineColor: '#BF4300',
    category: 'fiction',
    takeaway: 'The journey teaches you more than the destination. A reminder I carry into every new project and city.',
  },
  {
    id: 'zero-to-one',
    title: 'Zero to One',
    author: 'Peter Thiel',
    coverColor: '#1565C0',
    spineColor: '#0D47A1',
    category: 'leadership',
    takeaway: 'Building something truly new requires thinking from first principles, not iterating on what exists.',
  },
  // Fiction - John Green
  {
    id: 'looking-for-alaska',
    title: 'Looking for Alaska',
    author: 'John Green',
    coverColor: '#1A8870',
    spineColor: '#136B59',
    category: 'fiction',
    takeaway: 'The labyrinth of suffering and the beauty of seeking — a book that stays with you long after the last page.',
  },
  {
    id: 'fault-in-our-stars',
    title: 'The Fault in Our Stars',
    author: 'John Green',
    coverColor: '#2196F3',
    spineColor: '#1565C0',
    category: 'fiction',
    takeaway: 'Some infinities are bigger than other infinities. A meditation on love, loss, and what we leave behind.',
  },
  // Literary fiction
  {
    id: 'palace-of-illusions',
    title: 'The Palace of Illusions',
    author: 'Chitra Banerjee Divakaruni',
    coverColor: '#9C27B0',
    spineColor: '#7B1FA2',
    category: 'fiction',
    takeaway: 'The Mahabharata retold through Draupadi\'s eyes — power, desire, and the cost of destiny.',
  },
  {
    id: 'silent-honor',
    title: 'Silent Honor',
    author: 'Danielle Steel',
    coverColor: '#C62828',
    spineColor: '#8E0000',
    category: 'fiction',
    takeaway: 'A story of resilience during one of history\'s darkest chapters — honor in the face of injustice.',
  },
  {
    id: 'song-of-achilles',
    title: 'The Song of Achilles',
    author: 'Madeline Miller',
    coverColor: '#FF8F00',
    spineColor: '#E65100',
    category: 'fiction',
    takeaway: 'A retelling of the Iliad that makes you feel every moment of love and war. Devastatingly beautiful.',
  },
  {
    id: 'seven-husbands',
    title: 'The Seven Husbands of Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    coverColor: '#D4AF37',
    spineColor: '#B8960C',
    category: 'fiction',
    takeaway: 'Glamour, ambition, and the hidden truths we carry — a masterclass in storytelling and character.',
  },
  {
    id: 'pride-and-prejudice',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    coverColor: '#5C6BC0',
    spineColor: '#3949AB',
    category: 'fiction',
    takeaway: 'The original enemies-to-lovers. Austen\'s wit and social commentary remain razor-sharp centuries later.',
  },
  {
    id: 'bell-jar',
    title: 'The Bell Jar',
    author: 'Sylvia Plath',
    coverColor: '#455A64',
    spineColor: '#263238',
    category: 'fiction',
    takeaway: 'A haunting, honest portrayal of a brilliant mind struggling against the world\'s expectations.',
  },
  {
    id: 'perks-wallflower',
    title: 'The Perks of Being a Wallflower',
    author: 'Stephen Chbosky',
    coverColor: '#66BB6A',
    spineColor: '#43A047',
    category: 'fiction',
    takeaway: 'We accept the love we think we deserve. A coming-of-age story that captures the messy beauty of growing up.',
  },
  {
    id: 'harry-potter',
    title: 'Harry Potter (Series)',
    author: 'J.K. Rowling',
    coverColor: '#6A1B9A',
    spineColor: '#4A148C',
    category: 'fiction',
    takeaway: 'The series that made an entire generation fall in love with reading. Hogwarts will always be home.',
  },
  // Mystery - Agatha Christie
  {
    id: 'and-then-there-were-none',
    title: 'And Then There Were None',
    author: 'Agatha Christie',
    coverColor: '#37474F',
    spineColor: '#263238',
    category: 'mystery',
    takeaway: 'The queen of mystery at her finest — every page turns itself, and the ending rewrites everything.',
  },
  {
    id: 'murder-orient-express',
    title: 'Murder on the Orient Express',
    author: 'Agatha Christie',
    coverColor: '#4E342E',
    spineColor: '#3E2723',
    category: 'mystery',
    takeaway: 'The twist that set the gold standard for detective fiction. Poirot at his most brilliant.',
  },
  // History & War
  {
    id: 'guns-germs-steel',
    title: 'Guns, Germs, and Steel',
    author: 'Jared Diamond',
    coverColor: '#795548',
    spineColor: '#5D4037',
    category: 'history',
    takeaway: 'Why did history unfold differently on different continents? A sweeping answer that changes your worldview.',
  },
  {
    id: 'art-of-war',
    title: 'The Art of War',
    author: 'Sun Tzu',
    coverColor: '#B71C1C',
    spineColor: '#880E0E',
    category: 'history',
    takeaway: 'Ancient strategy that applies to everything from business to life. Know yourself, know your enemy.',
  },
];
