import type { Milestone } from '@/types/content';

export const milestones: Milestone[] = [
  {
    id: 'jntu',
    date: 'Dec 2020 – May 2024',
    year: 2020,
    title: 'JNTU Hyderabad',
    subtitle: 'B.Tech. in CS & Engineering (Data Science) - CGPA: 9.49/10',
    description: {
      recruiter: 'Completed B.Tech. in Computer Science and Engineering (Data Science) at Jawaharlal Nehru Technological University (JNTU), Hyderabad with a CGPA of 9.49/10.',
      explorer: 'College wasn\'t just coursework - it was a launchpad. I arrived knowing C and left knowing how to build systems, lead teams, and win under pressure. Four years of building, competing, leading, and growing.',
    },
    type: 'education',
    icon: '🎓',
    tags: ['B.Tech', 'Data Science', 'CGPA 9.49/10', 'Hyderabad'],
  },
  {
    id: 'mun-victory',
    date: '2019',
    year: 2019,
    title: 'First Place at MUN',
    subtitle: 'Learning to argue with evidence',
    description: {
      recruiter: 'Won first place in Model United Nations, developing persuasion and structured argumentation skills.',
      explorer: 'MUN taught me that the best argument isn\'t the loudest - it\'s the most structured. That skill transfers directly to system design reviews, research presentations, and product pitches.',
    },
    type: 'achievement',
    icon: '🏆',
    tags: ['public speaking', 'debate', 'first place'],
  },
  {
    id: 'nasa-space-apps',
    date: '2019',
    year: 2019,
    title: 'NASA Space Apps Hackathon',
    subtitle: 'Chandigarh nationals',
    description: {
      recruiter: 'Won NASA Space Apps Hackathon regional round and advanced to nationals in Chandigarh.',
      explorer: 'Building something for a NASA challenge felt like the scope of ambition I\'d always wanted. Traveling to Chandigarh for nationals was the first time I realized: this work can take me places - literally and figuratively.',
    },
    type: 'achievement',
    icon: '🚀',
    tags: ['hackathon', 'NASA', 'nationals', 'Chandigarh'],
  },
  {
    id: 'code-for-good',
    date: '2020',
    year: 2020,
    title: 'Code for Good',
    subtitle: 'The win that changed everything',
    description: {
      recruiter: 'Won JPMorgan Chase Code for Good national hackathon in second year, leading to an internship offer.',
      explorer: 'Second-year students don\'t usually win national hackathons against final-year teams. But we did - and that win opened the door to JPMorgan Chase. It proved that hunger and clarity beat experience when you\'re solving the right problem.',
    },
    type: 'achievement',
    icon: '💻',
    tags: ['hackathon', 'JPMorgan', 'national winner'],
    linkedProject: 'rasa-virtual-assistant',
  },
  {
    id: 'literaria-president',
    date: '2021',
    year: 2021,
    title: 'President, Literaria Clava',
    subtitle: 'Leading through literature',
    description: {
      recruiter: 'Rose through ranks to become President of the college literature club, organizing events and mentoring juniors.',
      explorer: 'Literature isn\'t a hobby separate from engineering - it\'s where I learned to think in narratives, build arguments, and understand what moves people. Leading Literaria Clava taught me that good leadership feels like good editing: you make others\' work shine.',
    },
    type: 'leadership',
    icon: '📚',
    tags: ['leadership', 'literature', 'president'],
  },
  {
    id: 'women-leadership',
    date: '2022',
    year: 2022,
    title: 'Women Leadership Conclave',
    subtitle: 'Chairing conversations that matter',
    description: {
      recruiter: 'Chaired the Women Leadership Conclave, organizing speakers and panels on women in technology.',
      explorer: 'Chairing the Women Leadership Conclave wasn\'t about a title - it was about creating space for conversations that don\'t happen enough. The conclave brought together leaders across industries and gave students a stage to ask the hard questions.',
    },
    type: 'leadership',
    icon: '✨',
    tags: ['leadership', 'women in tech', 'event organization'],
  },
  {
    id: 'jpmc-internship',
    date: 'Jan 2024 – Jun 2024',
    year: 2024,
    title: 'JPMC - Software Engineering Intern',
    subtitle: 'LLM chatbot & real-time data streaming',
    description: {
      recruiter: 'Engineered an LLM-powered incident chatbot reducing resolution time by 60%. Developed a real-time data streaming application with Java and Apache Kafka for 70+ downstream applications.',
      explorer: 'Walking into one of the world\'s largest financial institutions as an intern was humbling. I built an LLM chatbot that actually helped engineers during incidents, and a Kafka streaming platform serving 70+ apps. Walking out with a full-time offer felt earned.',
    },
    type: 'work',
    icon: '🏢',
    tags: ['JPMorgan Chase', 'LLM', 'Kafka', 'intern'],
    linkedProject: 'llm-incident-chatbot',
  },
  {
    id: 'jpmc-fulltime',
    date: 'Jul 2024 – Aug 2025',
    year: 2024,
    title: 'JPMC - Software Development Engineer I',
    subtitle: 'RASA NLU assistant & production CI/CD',
    description: {
      recruiter: 'Architected a RASA NLU virtual assistant eliminating 320+ hours/quarter of manual data entry. Built Java/AWS microservices cutting provisioning time by 40%. Hardened CI/CD pipelines achieving 99.9% uptime SLA.',
      explorer: 'They started calling me "the chatbot girl" - not as a joke, but as recognition. I took early proof-of-concepts that others had shelved and turned them into production systems handling real user queries at enterprise scale. That reputation was built one deploy at a time.',
    },
    type: 'work',
    icon: '🤖',
    tags: ['RASA', 'AWS', 'Java', 'CI/CD', 'enterprise'],
    linkedProject: 'rasa-virtual-assistant',
  },
  {
    id: 'aws-certification',
    date: 'Dec 2024',
    year: 2024,
    title: 'AWS Certified Cloud Practitioner',
    subtitle: 'Cloud fundamentals validated',
    description: {
      recruiter: 'Earned AWS Certified Cloud Practitioner certification, validating cloud architecture and services knowledge.',
      explorer: 'Getting AWS certified was about validating what I\'d already been building in production - but the structured learning filled in gaps I didn\'t know I had.',
    },
    type: 'achievement',
    icon: '☁️',
    tags: ['AWS', 'certification', 'cloud'],
  },
  {
    id: 'asu-journey',
    date: 'Aug 2025 – May 2027',
    year: 2025,
    title: 'ASU - M.S. Computer Science',
    subtitle: 'GPA: 4.0/4.0',
    description: {
      recruiter: 'Enrolled in M.S. Computer Science at Arizona State University with a 4.0 GPA. Coursework: NLP, Foundations of Algorithms, Information Assurance & Security.',
      explorer: 'I could have stayed comfortable at JPMC. But every chatbot I built made me want to understand the deeper mechanics - why do models hallucinate? How do you build agents that actually reason? ASU was the answer: a place to turn questions into research.',
    },
    type: 'education',
    icon: '🌵',
    tags: ['ASU', 'M.S.', 'NLP', '4.0 GPA'],
  },
  {
    id: 'research-projects',
    date: '2025',
    year: 2025,
    title: 'Research & Building',
    subtitle: 'LLMs, agents, and orchestration',
    description: {
      recruiter: 'Conducting research on agentic workflows, multi-retriever memory orchestration (Recall@5: 0.83 on LongMemEval), and STaR reasoning (46.2% on GSM8K).',
      explorer: 'At ASU, every project is a different kind of puzzle. Building agentic systems that plan and execute. Teaching models to reason step by step. Building memory systems that actually remember. The thread connecting them all: making AI more reliable, more autonomous, and more useful.',
    },
    type: 'work',
    icon: '🔬',
    tags: ['LLM', 'agents', 'RAG', 'research'],
    linkedProject: 'memory-augmented-llm',
  },
  {
    id: 'acm-leadership',
    date: '2025',
    year: 2025,
    title: 'ACM @ ASU',
    subtitle: 'Director of Engagement',
    description: {
      recruiter: 'Serving as Director of Engagement for ACM at ASU, organizing technical events and fostering community.',
      explorer: 'Leading ACM at ASU means building the kind of community I wish I\'d had earlier - where someone can walk in curious and leave connected. It\'s the same energy as Literaria Clava, just with more Python and fewer sonnets.',
    },
    type: 'leadership',
    icon: '🌐',
    tags: ['ACM', 'leadership', 'community', 'ASU'],
  },
];
